# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: self
      type: git
      name: cdp-datafreshness-functionspipelines
      ref: refs/heads/master
      # trigger: none
      trigger:
        branches:
          include:
            - main
            - develop
            - master
            - release/*
    - repository: app
      type: github
      endpoint: github.com_IN010124934_EYGS
      name: cdp-datafreshness-functions
      #ref: refs/heads/
      trigger:
        branches:
          include:
            - main
            - develop
            - master
            - release/*

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
