# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: self
      type: git
      name: PR trigger-GitHub
      # trigger: none
      trigger:
        branches:
          include:
            - main
           
    - repository: app
      type: github
      endpoint: Ghub
      name: trigger
      #ref: refs/heads/
      trigger:
        branches:
          include:
            - main
            - dev
            

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
